<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Account Statement - {{ $account->account_number }}</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #333;
        }
        .header h1 {
            font-size: 24px;
            margin: 0;
            color: #1a56db;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .info-grid {
            display: table;
            width: 100%;
            margin-bottom: 30px;
            border-collapse: collapse;
        }
        .info-row {
            display: table-row;
        }
        .info-cell {
            display: table-cell;
            padding: 10px;
            border: 1px solid #ddd;
        }
        .info-label {
            font-weight: bold;
            background-color: #f9fafb;
            width: 30%;
        }
        .summary-section {
            margin-bottom: 30px;
        }
        .summary-grid {
            display: table;
            width: 100%;
            border-collapse: collapse;
        }
        .summary-item {
            display: table-cell;
            padding: 15px;
            border: 1px solid #ddd;
            text-align: center;
        }
        .summary-label {
            font-size: 10px;
            color: #666;
            margin-bottom: 5px;
        }
        .summary-value {
            font-size: 16px;
            font-weight: bold;
        }
        .summary-positive {
            color: #059669;
        }
        .summary-negative {
            color: #dc2626;
        }
        table.transactions {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        table.transactions th {
            background-color: #f3f4f6;
            padding: 12px;
            text-align: left;
            font-size: 11px;
            font-weight: bold;
            border: 1px solid #ddd;
        }
        table.transactions td {
            padding: 10px;
            border: 1px solid #ddd;
            font-size: 11px;
        }
        table.transactions tr:nth-child(even) {
            background-color: #f9fafb;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .debit {
            color: #dc2626;
        }
        .credit {
            color: #059669;
        }
        .footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 10px;
            color: #666;
            text-align: center;
        }
        .signature-line {
            margin-top: 40px;
            border-top: 1px solid #333;
            width: 200px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>ACCOUNT STATEMENT</h1>
        <p>Generated on: {{ $generatedAt->format('F j, Y H:i:s') }}</p>
        <p>Generated by: {{ $generatedBy->full_name }}</p>
    </div>

    <div class="info-grid">
        <div class="info-row">
            <div class="info-cell info-label">Account Holder:</div>
            <div class="info-cell">{{ ucwords($customer->full_name) }}</div>
            <div class="info-cell info-label">Customer ID:</div>
            <div class="info-cell">{{ $customer->customer_number }}</div>
        </div>
        <div class="info-row">
            <div class="info-cell info-label">Account Number:</div>
            <div class="info-cell">{{ $account->account_number }}</div>
            <div class="info-cell info-label">Account Type:</div>
            <div class="info-cell">{{ $account->accountType->name ?? 'N/A' }}</div>
        </div>
        <div class="info-row">
            <div class="info-cell info-label">Currency:</div>
            <div class="info-cell">{{ $account->currency }}</div>
            <div class="info-cell info-label">Statement Period:</div>
            <div class="info-cell">{{ Carbon\Carbon::parse($startDate)->format('d M Y') }} - {{ Carbon\Carbon::parse($endDate)->format('d M Y') }}</div>
        </div>
        <div class="info-row">
            <div class="info-cell info-label">Opening Balance:</div>
            <div class="info-cell">{{ $account->currency }} {{ number_format($openingBalance, 2) }}</div>
            <div class="info-cell info-label">Closing Balance:</div>
            <div class="info-cell">{{ $account->currency }} {{ number_format($closingBalance, 2) }}</div>
        </div>
    </div>

    <div class="summary-section">
        <h3>Period Summary</h3>
        <div class="summary-grid">
            <div class="summary-item">
                <div class="summary-label">Total Credits</div>
                <div class="summary-value credit">{{ $account->currency }} {{ number_format($totalCredits, 2) }}</div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Total Debits</div>
                <div class="summary-value debit">{{ $account->currency }} {{ number_format($totalDebits, 2) }}</div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Net Change</div>
                @php $netChange = $totalCredits - $totalDebits; @endphp
                <div class="summary-value {{ $netChange >= 0 ? 'credit' : 'debit' }}">
                    {{ $account->currency }} {{ number_format($netChange, 2) }}
                </div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Transaction Count</div>
                <div class="summary-value">{{ $transactions->count() }}</div>
            </div>
        </div>
    </div>

    <h3>Transaction Details</h3>
    <table class="transactions">
        <thead>
            <tr>
                <th>Date</th>
                {{-- <th>Reference</th> --}}
                <th>Description</th>
                <th>Type</th>
                <th class="text-right">Debit (Out)</th>
                <th class="text-right">Credit (In)</th>
                <th class="text-right">Balance</th>
            </tr>
        </thead>
        <tbody>
            @php
                $balance = $openingBalance;
                $sortedTransactions = $transactions->sortBy('initiated_at');
            @endphp

            <!-- Opening Balance Row -->
            <tr>
                <td colspan="5" style="text-align: right; font-weight: bold;">Opening Balance:</td>
                <td class="text-right"><strong>{{ $account->currency }} {{ number_format($balance, 2) }}</strong></td>
            </tr>

            @foreach($sortedTransactions as $transaction)
                @php
                    $isCredit = $transaction->destination_account_id == $account->id;
                    $isDebit = $transaction->source_account_id == $account->id;
                    
                    if ($isCredit) {
                        $balance += $transaction->amount;
                    } elseif ($isDebit) {
                        $balance -= $transaction->amount;
                    }
                @endphp
                <tr>
                    <td>{{ $transaction->initiated_at->format('d M Y H:i') }}</td>
                    {{-- <td>{{ $transaction->transaction_reference }}</td> --}}
                    <td>{{ $transaction->description }}</td>
                    <td>{{ ucfirst(str_replace('_', ' ', $transaction->type)) }}</td>
                    <td class="text-right debit">
                        @if($isDebit)
                            {{ $account->currency }} {{ number_format($transaction->amount, 2) }}
                        @else
                            -
                        @endif
                    </td>
                    <td class="text-right credit">
                        @if($isCredit)
                            {{ $account->currency }} {{ number_format($transaction->amount, 2) }}
                        @else
                            -
                        @endif
                    </td>
                    <td class="text-right"><strong>{{ $account->currency }} {{ number_format($balance, 2) }}</strong></td>
                </tr>
            @endforeach

            <!-- Closing Balance Row -->
            <tr>
                <td colspan="5" style="text-align: right; font-weight: bold;">Closing Balance:</td>
                <td class="text-right"><strong>{{ $account->currency }} {{ number_format($balance, 2) }}</strong></td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        <p>This statement is system generated and does not require a physical signature.</p>
        <p>For any discrepancies, please contact your branch within 30 days.</p>
        
        <div style="margin-top: 40px;">
            <div style="float: left; width: 45%;">
                <div class="signature-line"></div>
                <p style="margin-top: 5px;">Customer Signature</p>
            </div>
            <div style="float: right; width: 45%;">
                <div class="signature-line"></div>
                <p style="margin-top: 5px;">Bank Official Signature</p>
            </div>
            <div style="clear: both;"></div>
        </div>
    </div>
</body>
</html>